apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: titanic
  name: db-data-pv
  labels:
    type: local
spec:
  storageClassName: generic
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db"