apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-db
  name: mongo-service
  namespace: titanic
spec:
  type: ClusterIP
  selector:
      app: mongoseed-pod
  ports:
  - port: 27017
    targetPort: 27017