apiVersion: v1
kind: Service
metadata:
  labels:
    app: titanic-api
  name: titanic-service
  namespace: titanic
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "9229"
    port: 9229
    targetPort: 9229
  selector:
    app: titanic-api
  type: LoadBalancer